include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "**/generated_plugin_registrant.dart"
  errors:
    invalid_annotation_target: ignore

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 25
    maximum-nesting-level: 9
    number-of-parameters: 4
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else

linter:
  rules:
    avoid_returning_null_for_future: true
    avoid_print: true
    cancel_subscriptions: true
    avoid_empty_else: true
    literal_only_boolean_expressions: true
    prefer_relative_imports: true
    unnecessary_statements: true
    always_declare_return_types: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_multiple_declarations_per_line: true
    avoid_positional_boolean_parameters: false
    avoid_redundant_argument_values: true
    avoid_void_async: true
    directives_ordering: false
    no_leading_underscores_for_library_prefixes: true
    # omit_local_variable_types: true
    package_api_docs: true
    # prefer_expression_function_bodies: true
    # prefer_final_parameters: true
    prefer_if_elements_to_conditional_expressions: true
    # prefer_interpolation_to_compose_strings: true

    prefer_function_declarations_over_variables: false
    sort_pub_dependencies: false
    overridden_fields: false
    avoid_classes_with_only_static_members: false
    constant_identifier_names: false
    require_trailing_commas: false
    noop_primitive_operations: false
    depend_on_referenced_packages: false
    use_build_context_synchronously: false
    avoid_setters_without_getters: false
